### PR TITLE
Add changelog for 0.13.0

### PR DESCRIPTION
**Pull request by consideRatio**
Cut a release?

---

#### Enhancements made

* Ensure oauthenticator.tests is packaged [#407](https://github.com/jupyterhub/oauthenticator/pull/407) ([@manics](https://github.com/manics))
* Auth0: Add refresh and id tokens to auth_state [#393](https://github.com/jupyterhub/oauthenticator/pull/393) ([@biomath-vlad](https://github.com/biomath-vlad))

#### Bugs fixed

* PyJWT 2.0 compliant [#402](https://github.com/jupyterhub/oauthenticator/pull/402) ([@rragundez](https://github.com/rragundez))

### CODE REVIEW

**Comment by yuvipanda** [comment]
Quick new releases, wheeee! :D Thanks, @consideRatio :) Will you push to PyPI, make tags, etc?

**Comment by consideRatio** [comment]
@yuvipanda https://pypi.org/project/oauthenticator/ :tada:!!

**Comment by yuvipanda** [comment]
Thank you!

**Comment by sjdemartini** [comment]
@consideRatio Thanks so much for releasing the updated version (in particular want to take advantage of the PyJWT 2.0 compliance). I noticed that the 0.13 version isn't yet available on conda-forge, however: https://anaconda.org/conda-forge/oauthenticator (still on 0.12.3). Are you able to update it there as well? Thanks again

**Comment by consideRatio** [comment]
I just merged https://github.com/conda-forge/oauthenticator-feedstock/pull/10/files so it should be out soon!

**Comment by sjdemartini** [comment]
Awesome, thanks @consideRatio!

**Pull request merged**
