### PR TITLE
Add Yandex.Passport authenticator

### PR DESCRIPTION
**Pull request by kidig**
Authorization via Yandex (https://oauth.yandex.com)

### CODE REVIEW

**Comment by kidig** [comment]
Sure. I already fixed it ;)

**Comment by kidig** [comment]
@minrk Hi. How about to merge that PR? ;)

**Comment by nickshch** [comment]
@minrk 🆙 
Our project needs this auth method.

**Comment by consideRatio** [comment]
This LGTM! Merge @minrk ?

**Comment by minrk** [comment]
Since Yandex can be implemented via GenericOAuthenticator, per #313, I think we will release oauthenticator 0.10 with documentation for configuring Yandex via Generic OAuth (which already works with 0.9) rather than this dedicated YandexOAuthenticator class

**Pull request merged**
