### PR TITLE
Relocate tests to the root repo directory

### PR DESCRIPTION
**Pull request by GeorgianaElena**
Ref: https://github.com/jupyterhub/oauthenticator/pull/552#issuecomment-1327421312 and https://github.com/jupyterhub/team-compass/issues/588

### CODE REVIEW

**Review by consideRatio — COMMENTED** [review]
I'm not confident about merging this. I see that there is mocks.py with things that I think could be relevant and used by someone downstream developing their own subclass, but I'm not sure.

If nobody is using these things, it is fine to merge in my mind, but its hard to know if someone does.

I searched for `oauthenticator.tests.mocks` and got two hits.

- This doesn't look like a problem, unsure what it is but its just listing a lot of stuff:
  https://github.com/search?q=oauthenticator.tests.mocks&type=code
- This on the other hand would be a problem, making it a breaking change.
  https://github.com/brazil-data-cube/bdc-jupyterhub-oauth

**Comment by manics** [comment]
I think we should make the decision based on how we intend the tests to be used or not used, taking into account all the points raised in https://github.com/jupyterhub/team-compass/issues/588

If we merge this it should be highlighted as a breaking change in a major release. It's disruptive to anyone relying on importing tests, but if we're keeping it as supported that implies we should avoid making breaking changes to the tests in a minor release, and potentially increases the maintenance burden (what parts of the tests are considered public and reusable?)

Either option is fine as long as it's carefully considered.

**Comment by consideRatio** [comment]
I figure this is a judgement call, I'm okay with either merge or close, leaning towards wanting to do what other people opine towards.

@GeorgianaElena how do you think about this at the moment?

**Comment by GeorgianaElena** [comment]
Given the context in https://github.com/jupyterhub/team-compass/issues/588, I believe I will close this and stick to the rule of having the tests dir in the top level directory for new projects.

Thanks a lot for all your input @consideRatio and @manics!

**Pull request closed without merging**
