### PR TITLE
Add KeycloakOAuthenticator

### PR DESCRIPTION
**Pull request by niveau0**
A possible implementation of a keycloak authenticator. Might be a solution for issue #107

### CODE REVIEW

**Comment by yuvipanda** [comment]
Thanks for the PR, @niveau0!
 
Does the generic oauthenticator not work by itself? According to https://github.com/jupyterhub/oauthenticator/pull/81 and @rafael-ladislau it does!

**Comment by rafael-ladislau** [comment]
If you set these lines in your jupyterhub_config.py:

```
from oauthenticator.generic import GenericOAuthenticator
c.JupyterHub.authenticator_class = GenericOAuthenticator
c.GenericOAuthenticator.login_service = 'You Service Name'
```

And set these environment variables before run JupyterHub:

```
OAUTH2_AUTHORIZE_URL=https://localhost:8080/auth/realms/master/protocol/openid-connect/auth
OAUTH2_TOKEN_URL=https://localhost:8080/auth/realms/master/protocol/openid-connect/token
OAUTH2_USERNAME_KEY=preferred_username
OAUTH_CLIENT_SECRET=<KEYCLOAK_CLIENT_SECRET>
OAUTH_CALLBACK_URL=https://<JUPYTERHUB_URL>/hub/oauth_callback
OAUTH2_USERDATA_URL=https://localhost:8080/auth/realms/master/protocol/openid-connect/userinfo
OAUTH_CLIENT_ID=<KEYCLOAK_CLIENT_ID>
```

The authentication should work with Keycloak.

**Comment by niveau0** [comment]
Ah thanks, that would be great. I will try that. My implementation is an old one, so maybe something changed in the meantime? Whatever, I try it and close this if it works, thanks a lot.

**Comment by minrk** [comment]
How did it go with the generic auth? Would you like to turn this into a docs PR for enabling keycloak via config?

**Comment by willingc** [comment]
@niveau0 How's it going with keycloak and the generic authenticator?

**Comment by niveau0** [comment]
@willingc Sorry for late reply, I will test it the next days, there was no time for now

**Comment by consideRatio** [comment]
@niveau0  thank you for making this PR!

We have made a decision to not add more specific classes for various identity provides within this repository, but instead attempt to make a few generically adjustable. We suggest that additional identity provider specific classes are made in standalone repositories going onwards.

For Keycloak specifically, it seems to be possible to use the generic oauthenticator class. Due to this, I'll close this PR.

Thank you for contributing to the Jupyter ecosystem @niveau0! :heart:

**Pull request closed without merging**
