### PR TITLE
Checking Globus Identity Set for Username

### PR DESCRIPTION
**Pull request by rpwagner**
@NickolausDS I ran into an issue where the username for the identity provider was in the identity set and not the `preferred_username`. I added a loop over the linked identities when `identity_provider` is defined. The `preferred_username` will still be used when that isn't defined. I added a test for this.

### CODE REVIEW

**Comment by NickolausDS** [comment]
Thanks! Could you share which providers you're using? I'd like to dig into why `preferred_username` doesn't get populated for some providers and not others.

**Comment by rpwagner** [comment]
Hi Nick!

The `preferred_username` gets populated, but there's no guarantee it will be from the desired IdP set via `identity_provider`. My `userinfo` is below, from an app with XSEDE set as the required IdP. However, the "top level" `userinfo` comes from UCSD. This is something I recall from Globus Auth: that the specific IdP used to generate the OIDC `userinfo` is effectively random, and that you need to introspect the identity set to get things from a specific IdP. @ericblau saw this when adding session support. This is a step in that direction.

--RIck

```json
{
    "email": "rpwagner@ucsd.edu",
    "preferred_username": "046f34a240f0615e01420b3ff4350922@ucsd.edu",
    "identity_provider_display_name": "University of California-San Diego",
    "sub": "15f4b3e7-61a3-4d2e-8ecc-7670c2dc1761",
    "name": "Richard Wagner",
    "last_authentication": 1601328660,
    "identity_set": [{"email": "rick@ucsd.edu",
		      "identity_provider_display_name": "Globus ID",
		      "name": "Rick Wagner",
		      "organization": "University of California, San Diego",
		      "username": "rpwagner@globusid.org",
		      "sub": "c4e16e62-d274-11e5-b9e9-cf0225068ce8",
		      "last_authentication": 1601415666,
		      "identity_provider": "41143743-f3c8-4d60-bbdb-eeecaba85bd9"},
		     {"email": "rpwagner@ucsd.edu",
		      "identity_provider_display_name": "University of California-San Diego",
		      "sub": "15f4b3e7-61a3-4d2e-8ecc-7670c2dc1761",
		      "name": "Richard Wagner",
		      "username": "046f34a240f0615e01420b3ff4350922@ucsd.edu",
		      "last_authentication": 1601328660,
		      "identity_provider": "bf6d9bc7-8ce6-4421-b521-fed8e9ccaad0"},
		     {"email": null,
		      "identity_provider_display_name": "Argonne LCF",
		      "sub": "c4ae3699-07ba-4fda-8c8a-eaeb908d0a17",
		      "name": null,
		      "username": "rpwagner@alcf.anl.gov",
		      "last_authentication": 1573158770,
		      "identity_provider": "b58b196e-c9fe-11e5-a528-8c705ad34f60"},
		     {"email": "rick@ucsd.edu",
		      "identity_provider_display_name": "XSEDE",
		      "name": "Richard Wagner",
		      "organization": "University of California, San Diego",
		      "username": "rpwagner@xsede.org",
		      "sub": "c4e1bd36-d274-11e5-b9ea-370f0741285c",
		      "last_authentication": 1601401303,
		      "identity_provider": "36007761-2cf2-4e74-a068-7473afc1d054"},
		     {"email": null,
		      "identity_provider_display_name": "ORCID",
		      "sub": "d063e8b4-d6fe-419c-bdc3-417be8796933",
		      "name": "Rick Wagner",
		      "username": "0000-0003-1291-5876@orcid.org",
		      "last_authentication": 1555429322,
		      "identity_provider": "0519206d-f21c-4771-990a-282a12bb666b"},
		     {"email": "richard.p.wagner@gmail.com",
		      "identity_provider_display_name": "Google",
		      "name": "Rick Wagner",
		      "organization": "University of California, San Diego",
		      "username": "richard.p.wagner@gmail.com",
		      "sub": "c4e207b4-d274-11e5-b9eb-b3d600411c2f",
		      "last_authentication": 1600794136,
		      "identity_provider": "29ca0ba0-c770-403d-8827-8224fbee302a"}],
    "identity_provider": "bf6d9bc7-8ce6-4421-b521-fed8e9ccaad0"
}
```

**Comment by rpwagner** [comment]
I tested this by registering a Native App based on [the FAIR Research Login CLI example](https://github.com/fair-research/native-login/blob/master/examples/example_cli.py), setting the IdP in the Globus Auth app registration, and modifying the `hello` function.

```python
    def say_hello(self):
        # Loads RefreshTokenAuthorizer if login(refresh_tokens=True), otherwise
        # will load an AccessTokenAuthorizer
        ac_authorizer = self.get_authorizers()['auth.globus.org']
        auth_cli = AuthClient(authorizer=ac_authorizer)
        user_info = auth_cli.oauth2_userinfo()
        username, domain = user_info['preferred_username'].split('@', 1)
        print('Hello {} (preferred) from {}! How are you today?'.format(username, domain))
        for identity in user_info['identity_set']:
            username, domain = identity['username'].split('@', 1)
            print('Hello {} from {}! How are you today?'.format(username, domain))
        print()
        print(user_info.text) 
````

**Comment by rpwagner** [comment]
@NickolausDS not to confuse things, but I was able to get Globus Auth sessions working by creating a Globus-specific login handler. This may be worth including as an option. However, while this did what was expected by requiring login against a particular IdP, the `preferred_username` was still from a different one.

```python
from .oauth2 import OAuthLoginHandler, OAuthenticator

class GlobusLoginHandler(OAuthLoginHandler):
    def authorize_redirect(self, *args, **kwargs):
        extra_params = kwargs.setdefault('extra_params', {})
        if self.authenticator.identity_provider:
            extra_params["session_required_single_domain"] = self.authenticator.identity_provider

        return super().authorize_redirect(*args, **kwargs)
```

```python
class GlobusOAuthenticator(OAuthenticator):
    """The Globus OAuthenticator handles both authorization and passing
    transfer tokens to the spawner. """

    login_service = 'Globus'
    login_handler = GlobusLoginHandler
    logout_handler = GlobusLogoutHandler
```

**Comment by NickolausDS** [comment]
Hi Rick,

For your earlier post about picking the correct `preferred_username`, this should always match the Required Identity on the Globus App, provided Required Identity was set when the Globus App was created. If "Required Identity" was set on an app after users have logged in, those users will be stuck with whichever identity they originally logged in with until they revoke their consents. It's easiest to create a new Globus App and immediately set Required Identity before any users login. It shouldn't be possible for users to login for the first time with an app with Required Identity set and end up with a different IdP. 

For the latter post about Globus Sessions,  since #338 you can also pass authorization params via Jupyter config options:

```
c.LocalGlobusOAuthenticator.extra_authorize_params = {'session_required_single_domain': 'ucsd.edu'}
```

However, this _doesn't_ guarantee `preferred_username` will match the identity the user authenticated with, it will only force the user to login with that identity.

**Comment by rpwagner** [comment]
Hi Nick,

Thanks for the background on how `preferred_username` and the other `userinfo` fields are tied to the Required Identity selection. I had forgotten or not known about consents being an issue. I think that's what I was seeing as I worked with different IdPs and wasn't revoking my consents between changes to the client settings. I retested and it's things are fine! And the `extra_authorize_params` works as expected.

--Rick

**Pull request closed without merging**
