### PR TITLE
Add new AWSCognito Authenticator

### PR DESCRIPTION
**Pull request by jmartinc89**
Implementation of a custom authenticator for AWS Cognito.
Implements the whole Client authentication flow but also includes explicit logout

### CODE REVIEW

**Comment by martindurant** [comment]
It's great that you have done this! Is this just waiting for review, or something else?
I wonder, do the Cognito identity properties make it into the user's session? I mean, cognito in certain flows provides JWTs containing the tokens and claims for the given user - can you, in the context of the notebook pod, extract the claims?

**Comment by playermanny2** [comment]
this would be great to have...would def love a review on this :) @minrk @rgbkrk

**Comment by minrk** [comment]
Thank you!

**Comment by jmartinc89** [comment]
You are welcome!

**Pull request merged**
