### PR TITLE
Use OAuth2Mixin on base OAuthLoginHandler

### PR DESCRIPTION
**Pull request by consideRatio**
I struggled with understanding the Authenticator classes and ran into #250. This PR removes mixing in the OAuth2Mixin from tornado.auth unless it is actually used by the classes, and makes sure to mix it in when it is actually needed.

The PR seems functional to me without breaking any tests. But, I have not tested things on a JupyterHub and made an actual login to google etc though. Speaking of that, what would the best way to do that be? It is unreasonable to me to test all authenticator classes but perhaps I could setup and run a E2E test with say google auth. Please help me decide on the level of verification needed before merge.

### CODE REVIEW

**Comment by betatim** [comment]
I'm not sure I have an opinion on this :-/ I think it would be good to understand why it was done the way it is currently. It makes some amount of sense to my programmer brain to do things the original way (especially if we didn't cut off the comment in one of the docstrinngs ...).

Overall I wouldn't want to decide either way without having some input from the original creators @minrk and/or @rgbkrk. However they are both on leave at the moment :-/

**Comment by minrk** [comment]
It's a little confusing because we are mixing in generic implementations from two sources:

1. OAuth2Mixin which is a necessarily incomplete base class from tornado for a mixin that defines the API for `authorize_redirect` and `_OAUTH_AUTHORIZE_URL` etc.
2. OAuthLoginHandler, which is also an incomplete base class that calls `authorize_redirect`, thereby assuming final classes inherit from a completed OAuth2Mixin subclass
3. provider-specific mixins that should ~only set the values for `_OAUTH_AUTHORIZE_URL`

I think this PR is a step in the right direction, but it adds an additional complexity that the final Handler classes are now sensitive to inheritance order, because both parents (ProviderMixin and OAuthLoginHandler) define `_OAUTH_AUTHORIZE_URL`. I think it probably makes sense to go one step further and eliminate the ProviderMixins entirely and define the provider-specific `_OAUTH` attributes directly on the final Handler classes. Does that sound good?

**Comment by consideRatio** [comment]
@minrk a very concrete idea that currently makes sense to me! I'll work on it! I appreciate how clearly you can summarize and describe things :D

**Comment by consideRatio** [comment]
Closed in favor of suggested approach, which can be opened in another PR. See issue #312 to remember this going onwards.

**Pull request closed without merging**
