### PR TITLE
Add FeiShu Authenticator

### PR DESCRIPTION
**Pull request by harrywang**
FeiShu (https://www.feishu.cn/en/) is one of the most popular team collaboration tools developed by ByteDance (the company behind Tiktok). This PR enables OAuth authentication via FeiShu. We have tested this in our internal JupyterHub deployment at Tezign.com.

### CODE REVIEW

**Comment by manics** [comment]
Hi! Thanks for opening a PR.
I'm afraid we're not accepting new authenticators into this repository due to the testing and maintenance overhead, you can see some of the discussions in https://github.com/jupyterhub/oauthenticator/issues/313.

What we'd like everyone to do is to package new authenticators in their own python package, with oauthenticator as a dependency. This has the added advantage that it'll be easier for you to fix issues since you have full control over the repository, and you'll also be able to add full integration tests requiring secrets.

Please feel free to add a link in our docs though once it's published. Hope this makes sense!

**Comment by harrywang** [comment]
@manics this makes sense - Do you have an example of such a package? I searched around and could not find one - I want to follow an example to create the FeiShu package if possible. Thanks.

**Comment by manics** [comment]
@harrywang Here's a couple of examples:
- https://github.com/facebookincubator/jupyterhub_fb_authenticator
- https://github.com/swan-cern/jupyterhub-extensions/tree/c250978c7f2666c0caca7861d98c0747574f218f/KeyCloakAuthenticator

If you have any more questions would you mind asking on the community forum https://discourse.jupyter.org/ ? That way the rest of the community will benefit from the discussion, and it's also a chance for you to advertise your work :smile:

**Comment by harrywang** [comment]
@manics Thanks a lot. We will work on this :).

**Comment by harrywang** [comment]
@manics we have tested and published the FeiShu Authenticator and issued a PR #427 

Thanks!!

**Pull request closed without merging**
