### PR TITLE
Add CanvasOAuthenticator

### PR DESCRIPTION
**Pull request by yuvipanda**
Canvas is a very popular educational tool used to manage
classes in universities across the world. It has a very
rich API (https://canvas.instructure.com/doc/api/), and
deep integration with it makes a lot of things possible.

This Authenticator builds on top of GenericOAuthenticator,
but adds a few new features:

- Strip domain names specific user emails to get userids. Works
  when all your Canvas users have an email for your educational
  institution.
- Fetch list of courses the user is enrolled in, and what kind
  (student, TA, instructor, etc). This allows for finer
  grained access control, and modifying the user environment
  based on the courses they are enrolled in.
- Ability to restrict user logins based on what courses they
  are enrolled in.

I've added some unit tests, and things seem to be working out
ok.

### CODE REVIEW

**Comment by manics** [comment]
I don't, but I've long wished for an example that we could point people to. Maybe we can use this as a driver to sort out the test infrastructure?

Jupyter Notebook packages some of their test infrastructure inside the python package, e.g. for testing ContentManagers:
https://jupyter-notebook.readthedocs.io/en/stable/extending/contents.html#testing

Could we do something similar?

**Comment by manics** [comment]
This should let you do `from oauthenticator import tests`: https://github.com/jupyterhub/oauthenticator/pull/407

**Comment by manics** [comment]
Can we close this, or are there further barriers to developing external authenticators?

**Comment by consideRatio** [comment]
@yuvipanda do you have a status update on this? Is it published externally somewhere for example?

I'll go ahead and close it for now as I'm about to close another authenticator PR as well.

**Comment by yuvipanda** [comment]
i don't think i've put this up anywhere, I'll do that sometime in the next few weeks

**Pull request closed without merging**
